name: Build, Run, and Push Docker Image

on:
  push:
    branches: 
      - main
 
jobs:
  build-run-push:
    runs-on: self-hosted  # 👈 use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/sample-app:latest .

      - name: Run Docker Container
        run: sudo docker run -d --name mycontainer -p 80:80 ${{ secrets.DOCKER_USERNAME }}/sample-app:latest

      - name: Push to Docker Hub
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/sample-app:latest
